### ISSUE TITLE
Compile Failure: CSUNetSec/netsec-protobufs v0.1.4 lacks `bgpmonv2.Entity`

### ISSUE THREAD

**Issue by chickenandpork** [CSUNetSec/bgpmon#28]
https://github.com/CSUNetSec/bgpmon/blob/e67c7d7ae6c75c3bef74d53e87e16056734c665f/go.mod#L5

You can see in a PR such as https://github.com/CSUNetSec/netsec-protobufs/compare/v0.1.4...master that the `Entity` message is added after the v0.1.4 that listed in `go.mod` therefore `db/dbstructs.go` lines 193, 194, 227 cannot compile.

**Comment by WillYingling** [comment]
I've created a new tag for netsec-protobufs and updated the go.mod file, it should compile now.

**Comment by chickenandpork** [comment]
confirmed resolved in https://github.com/CSUNetSec/bgpmon/commit/bbac03bd9a89d82545f2b7b9e1520318ab76ff48 -- works fine for me now -- thanks!  so fast :o)
